import javax.inject.Inject;
import javax.ws.rs.GET;
import javax.ws.rs.Path;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'haochen' at '5/12/16 10:42 AM' with Gradle 2.13
 *
 * @author haochen, @date 5/12/16 10:42 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
